[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
memetoken_launchpad_solana = "EjsTq7pz5Q7xfpZyyBVYvH6zUkC1cRtKVbYtrjyj4QJ4"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/home/webexpert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/client.ts"
client = "yarn run ts-node client/clientTest.ts"
